CREATE TABLE IF NOT EXISTS genres(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)-- ограничение уникальности поставить
);

CREATE TABLE IF NOT EXISTS rating_mpa(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)-- ограничение уникальности поставить
);

CREATE TABLE IF NOT EXISTS films(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200),
    description varchar(200),
    duration int,
    releaseDate timestamp,
    genre_id INTEGER REFERENCES genres (id) ON DELETE RESTRICT,
    rating_id INTEGER REFERENCES rating_mpa (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(100),
    name varchar(200),
    email varchar(200),
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS friends(
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);